name: issues
on:
  issues:
    types: [labeled]
jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Update GitHub issue
        env:
          GITHUB_ORIGINAL_TITLE: ${{ github.event.issue.title }}
        run: echo $GITHUB_ORIGINAL_TITLE; ls -al; echo 'DONE'
