name: issues
on:
  issues:
    types: [labeled]
jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Update GitHub issue
        uses: actions/github-script@v2.0.0
        env:
          GITHUB_ORIGINAL_TITLE: ${{ github.event.issue.title }}
        with:
          script: const newTitle = `${process.env.GITHUB_ORIGINAL_TITLE}`
