name: issues
on:
  issues:
    types: [labeled]
jobs:
  add-comment:
    runs-on: ubuntu-latest
    env:
      GITHUB_ORIGINAL_TITLE: ${{ github.event.issue.title }}
    steps:
      - uses: actions/github-script@v2.0.0
      - name: Run Suggest
        with:
         script: |
            const newTitle = `${process.env.GITHUB_ORIGINAL_TITLE}`
